language: java
install: mvn install -DskipTests -Dgpg.skip
jdk:
  - oraclejdk8
addons:
  firefox: "48.0"
env:
  - DISPLAY=:99
script:
  - |
      export GECKODRIVER_VERSION=v0.11.1
      curl -L -o geckodriver.tar.gz https://github.com/mozilla/geckodriver/releases/download/${GECKODRIVER_VERSION}/geckodriver-${GECKODRIVER_VERSION}-linux64.tar.gz
      tar -xvzf geckodriver.tar.gz
      export GECKO_DRIVER_PATH=$(pwd)/geckodriver
  - mvn clean test -Dgpg.skip=true -Dgalen.use.fail.exit.code=false -Dwebdriver.gecko.driver=$GECKO_DRIVER_PATH
  - mvn verify -Dgpg.skip=true -Dgalen.use.fail.exit.code=false -Dwebdriver.gecko.driver=$GECKO_DRIVER_PATH
before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
after_failure:
  - find . -name "TestSuite.txt" | xargs cat
