language: java
install: mvn install -DskipTests -Dgpg.skip
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
addons:
  firefox: "38.0"
env:
  - DISPLAY=:99
script:
  - mvn clean test -Dgpg.skip=true -Dgalen.use.fail.exit.code=false
  - mvn verify -Dgpg.skip=true -Dgalen.use.fail.exit.code=false
before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
after_failure:
  - find . -name "TestSuite.txt" | xargs cat
