language: java
install: mvn install -DskipTests -Dgpg.skip
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
script:
  - mvn clean install verify -Dgpg.skip=true -Dgalen.use.fail.exit.code=false
before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
